// <auto-generated />
using BulkyBook.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulkyBook.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231009164458_addProductsToDb")]
    partial class addProductsToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BulkyBook.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "SciFi"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "History"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Duy"
                        });
                });

            modelBuilder.Entity("BulkyBook.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Billy Spark",
                            Description = "Description",
                            ISBM = "SWD99901",
                            Price = 99.0,
                            Price100 = 100.0,
                            Price50 = 66.0,
                            Title = "Fortune of time"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Alice Wonderland",
                            Description = "A thrilling adventure story",
                            ISBM = "ABC12345",
                            Price = 59.990000000000002,
                            Price100 = 39.990000000000002,
                            Price50 = 45.990000000000002,
                            Title = "The Great Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Chef Gordon Ramsay",
                            Description = "A cookbook for aspiring chefs",
                            ISBM = "XYZ67890",
                            Price = 79.989999999999995,
                            Price100 = 59.990000000000002,
                            Price50 = 65.989999999999995,
                            Title = "Cooking Mastery"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Historian Jane Smith",
                            Description = "A journey through history",
                            ISBM = "DEF54321",
                            Price = 49.990000000000002,
                            Price100 = 34.990000000000002,
                            Price50 = 39.990000000000002,
                            Title = "History Unveiled"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Dr. John Doe",
                            Description = "An introduction to science",
                            ISBM = "PQR98765",
                            Price = 69.989999999999995,
                            Price100 = 49.990000000000002,
                            Price50 = 55.990000000000002,
                            Title = "Science Explained"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
